[package]
name = "wasmer-bin-fuzz"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow = "1"
wasm-smith = "0.4.4"
libfuzzer-sys = "0.4.0"
wasmer = { path = "../lib/api", package = "near-vm" }
wasmer-compiler-singlepass = { path = "../lib/compiler-singlepass", package = "near-vm-compiler-singlepass", optional = true }
wasmer-engine-universal = { path = "../lib/engine-universal", package = "near-vm-engine-universal", optional = true }
wasmprinter = "0.2"

[features]
singlepass = [ "wasmer-compiler-singlepass" ]
universal = [ "wasmer-engine-universal" ]

[[bin]]
name = "equivalence_universal"
path = "fuzz_targets/equivalence_universal.rs"
required-features = ["universal"]

[[bin]]
name = "universal_singlepass"
path = "fuzz_targets/universal_singlepass.rs"
required-features = ["universal", "singlepass"]
