[package]
name = "near-vm-runner"
version = "0.0.0"
authors.workspace = true
publish = false
edition.workspace = true
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["wasm"]
repository = "https://github.com/nearprotocol/nearcore"
description = """
This crate implements the specification of the interface that Near blockchain exposes to the smart contracts.
"""

[dependencies]
anyhow = { workspace = true, optional = true }
borsh.workspace = true
loupe.workspace = true
memoffset.workspace = true
once_cell.workspace = true
parity-wasm.workspace = true
finite-wasm.workspace = true
serde.workspace = true
tracing.workspace = true
wasmparser.workspace = true
wasmtime = { workspace = true, optional = true }

near-cache = { path = "../../utils/near-cache" }
near-vm-logic = { path = "../near-vm-logic", default-features = false }
near-vm-errors = { path = "../near-vm-errors" }
near-primitives = { path = "../../core/primitives" }
near-stable-hasher = { path = "../../utils/near-stable-hasher" }

# Old versions of pwasm-utils we need to preserve backwards compatibility under
# old protocol versions.
pwasm-utils_12 = { package = "pwasm-utils", version = "0.12" }
parity-wasm_41.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
wasmer-runtime = { version = "0.18.0", features = ["default-backend-singlepass"], default-features = false, package = "wasmer-runtime-near", optional = true }
wasmer-runtime-core = { version = "0.18.2", package = "wasmer-runtime-core-near", optional = true}

# Use the following for development versions of Wasmer.
# wasmer-types = { package = "wasmer-types-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-compiler-singlepass = { package = "wasmer-compiler-singlepass-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-engine-universal = { package = "wasmer-engine-universal-near", git = "https://github.com/near/wasmer", branch = "near-main", optional = true }
# wasmer-vm = { package = "wasmer-vm-near", git = "https://github.com/near/wasmer", branch = "near-main" }
wasmer-compiler = { package = "wasmer-compiler-near", version = "=2.4.0", optional = true }
wasmer-compiler-singlepass = { package = "wasmer-compiler-singlepass-near", version = "=2.4.0", optional = true }
wasmer-engine = { package = "wasmer-engine-near", version = "=2.4.0", optional = true }
wasmer-engine-universal = { package = "wasmer-engine-universal-near", version = "=2.4.0", optional = true, features = ["compiler"] }
wasmer-types = { package = "wasmer-types-near", version = "=2.4.0", optional = true }
wasmer-vm = { package = "wasmer-vm-near", version = "=2.4.0", optional = true }

finite-wasm = "0.3.0"
prefix-sum-vec = "0.1.2"
near-vm-compiler = { package = "near-vm-compiler", path = "../near-vm/lib/compiler", optional = true }
near-vm-compiler-singlepass = { package = "near-vm-compiler-singlepass", path = "../near-vm/lib/compiler-singlepass", optional = true }
near-vm-engine = { package = "near-vm-engine", path = "../near-vm/lib/engine", optional = true }
near-vm-engine-universal = { package = "near-vm-engine-universal", path = "../near-vm/lib/engine-universal", features = ["compiler"], optional = true }
near-vm-types = { package = "near-vm-types", path = "../near-vm/lib/types", optional = true }
near-vm-vm = { package = "near-vm-vm", path = "../near-vm/lib/vm", optional = true }

[dev-dependencies]
arbitrary.workspace = true
assert_matches.workspace = true
bolero.workspace = true
expect-test.workspace = true
hex.workspace = true
rand.workspace = true
wasm-smith.workspace = true
wasmprinter.workspace = true
wat.workspace = true

near-test-contracts = { path = "../near-test-contracts" }

[features]
# all vms enabled for now
default = [
  "wasmer0_vm",
  "wasmtime_vm",
  "wasmer2_vm",
]
wasmer0_vm = [ "wasmer-runtime", "wasmer-runtime-core" ]
wasmtime_vm = [ "wasmtime", "anyhow"]
wasmer2_vm = [
    "wasmer-compiler",
    "wasmer-compiler-singlepass",
    "wasmer-engine",
    "wasmer-engine-universal",
    "wasmer-types",
    "wasmer-vm"
]
near_vm = [
    "near-vm-compiler",
    "near-vm-compiler-singlepass",
    "near-vm-engine",
    "near-vm-engine-universal",
    "near-vm-types",
    "near-vm-vm"
]

# Force usage of a specific wasm vm irrespective of protocol version.
force_wasmer0 = ["wasmer0_vm"]
force_wasmtime = ["wasmtime_vm"]
force_wasmer2 = ["wasmer2_vm"]
force_near_vm = ["near_vm"]

no_cpu_compatibility_checks = []

no_cache = []

protocol_feature_fix_contract_loading_cost = [
    "near-primitives/protocol_feature_fix_contract_loading_cost",
    "near-vm-logic/protocol_feature_fix_contract_loading_cost",
]

nightly = [
    "near-primitives/nightly",
    "protocol_feature_fix_contract_loading_cost",
]
sandbox = ["near-vm-logic/sandbox"]
io_trace = ["near-vm-logic/io_trace"]


[package.metadata.cargo-udeps.ignore]
# `no_cache` feature leads to an unused `cached` crate
normal = ["cached"]
